### ISSUE TITLE
Cool stuff

### ISSUE THREAD

**Issue by ionescu77** [AlexInntekt/RoundProgressBarWithLongPress#1]
Works like charm and I like it!

Not necesarelly an issue but nice to have:

- I see the button has a green and a red state
- the action RED is trigerred when the user takes away the finger from the button
- maybe the user will hold on to the button 5 minutes or more if he does not see a state change
- so the final action should be trigerred when the user has pressed the button long enough for the circle or the progress bar to be 100% completed/filled

Am I correct?

**Comment by AlexInntekt** [comment]
Yes, exactly.

The goal is that the final action will be triggered when and only when the circle is completed, (he can stop touching in that moment or even later on, it does not matter). Done.

-red/color says if the physical touch is present or not.
-after a complete cycle, everything get reset back and the desired function can get called.

-currently integrated in ChakraBase: Develop.

I tested it in different circumstances and it's exactely what I wanted. 

Danke
